# Generated by Django 3.2.5 on 2021-07-04 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bucket',
            field=models.IntegerField(choices=[(3, '7 days'), (5, '30 days'), (4, '16 days'), (1, '1 day'), (2, '3 days')], default=1),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
