# Generated by Django 3.2.5 on 2021-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bucket',
            field=models.IntegerField(choices=[(4, '16 days'), (1, '1 day'), (3, '7 days'), (5, '30 days'), (2, '3 days')], default=1),
        ),
    ]
